version: '3.7'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2g
    ports:
      - "4444:4444"

  app:
    build: .
    command:
      bash -c "sleep 3 & pyhton main.py"
    depends_on:
      - selenium-chrome
    volumes:
      - .:/app
