name: FormSeeker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run manually in "Actions"
  workflow_dispatch:

jobs:
  test:
    name: Automated Tests (Docker)
    runs-on: ubuntu-latest

    steps:
      # 1. download repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. install and configure docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. run tests
      # --build: ensures the image is built from scratch
      # --abort-on-container-exit: terminates Selenium as soon as the test finishes
      # --exit-code-from app: if Pytest fails, the pipeline fails
      - name: Run Pytest with Docker Compose
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app
